export const str = `a-: 不，缺乏（如 amoral, atypical）
ab-: 离开（如 absent, abduct）
ad-: 向，朝（如 advance, admit）
ante-: 在前（如 antecedent, antebellum）
anti-: 反对（如 antibiotic, antisocial）
auto-: 自己（如 autonomy, automobile）
bene-: 好，良好（如 beneficial, benevolent）
bi-: 两（如 bicycle, bilingual）
circum-: 周围（如 circumference, circumnavigate）
co-: 一起（如 cooperate, coexist）
contra-: 反对（如 contradict, contrary）
de-: 向下，去掉（如 devalue, dehydrate）
dis-: 否定，反向（如 disagree, disappear）
en-: 使，放入（如 enclose, enable）
ex-: 外，出去（如 extract, exhale）
fore-: 在前（如 forecast, foresee）
hyper-: 超过，过度（如 hyperactive, hyperlink）
il-: 不（如 illegal, illegible）
im-: 不（如 impossible, imperfect）
in-: 在，不（如 invisible, incorrect）
inter-: 在之间（如 interact, international）
intra-: 在内部（如 intravenous, intrastate）
macro-: 大（如 macroeconomics, macromolecule）
micro-: 小（如 microscope, microorganism）
mid-: 中间（如 midday, midterm）
mis-: 错误（如 misunderstand, mislead）
non-: 不（如 nonprofit, nonsense）
ob-: 反对（如 obstruct, obvious）
omni-: 全部（如 omniscient, omnipresent）
over-: 过度（如 overeat, overestimate）
pan-: 全部（如 panorama, pandemic）
peri-: 周围（如 perimeter, periscope）
post-: 在后（如 postpone, postscript）
pre-: 在前（如 preview, prepare）
pro-: 为了，支持（如 promote, proactive）
re-: 再，回（如 redo, revisit）
semi-: 半（如 semicircle, semiconductor）
sub-: 在下（如 submarine, substandard）
super-: 超级（如 superhuman, supermarket）
trans-: 穿越，转变（如 transport, transform）
tri-: 三（如 triangle, tricycle）
un-: 不，反（如 unhappy, undo）
under-: 不足（如 underestimate, underdeveloped）
up-: 向上（如 upgrade, uplift）
with-: 反对（如 withhold, withdraw）
anti-: 反（如 antifreeze, antibiotic）
de-: 除去（如 defrost, dehydrate）
ex-: 前（如 ex-boyfriend, exceed）
in-: 否定（如 incomplete, indecisive）
out-: 超过（如 outperform, outdated）
up-: 向上（如 upgrade, uplift）
bio-: 生命（如 biology, biography）
geo-: 地球（如 geography, geology）
thermo-: 热（如 thermometer, thermal）
photo-: 光（如 photograph, photosynthesis）
tele-: 远（如 telephone, television）
chrono-: 时间（如 chronology, synchronize）
psycho-: 心理（如 psychology, psychopath）
neuro-: 神经（如 neuroscience, neurotic）
cyber-: 网络（如 cyberspace, cybersecurity）
electro-: 电（如 electronic, electrolyte）
hydro-: 水（如 hydroelectric, hydrology）
thermo-: 热（如 thermostat, thermometer）
archeo-: 古（如 archaeology, archaeopteryx）
homo-: 同（如 homogeneous, homonym）
hetero-: 异（如 heterogeneous, heterosexual）
macro-: 大（如 macroeconomics, macromolecule）
micro-: 小（如 microbiology, microscope）
paleo-: 古老（如 paleontology, paleolithic）
retro-: 向后（如 retroactive, retrospective）
socio-: 社会（如 sociology, sociopath）
auto-: 自（如 autonomous, autobiography）
bio-: 生命（如 biome, biohazard）
chem-: 化学（如 chemistry, chemical）
physio-: 生理（如 physiology, physiotherapy）
techno-: 技术（如 technology, technician）
uni-: 一（如 unify, unilateral）
vol-: 意愿（如 volunteer, voluntary）
vis-: 看（如 visual, vision）
voc-: 声音（如 vocal, vocabulary）
xeno-: 外（如 xenophobia, xenon）
zoo-: 动物（如 zoology, zoo）
aero-: 空气（如 aerodynamics, aeroplane）
astro-: 星（如 astronomy, astrophysics）
cardio-: 心脏（如 cardiology, cardiovascular）
crypto-: 隐藏（如 cryptography, cryptocurrency）
dyna-: 力量（如 dynamic, dynasty）
gastro-: 胃（如 gastronomy, gastroenterology）
litho-: 石（如 lithography, monolith）
morpho-: 形状（如 morphology, metamorphosis）
patho-: 病（如 pathology, psychopath）
phon-: 声音（如 phonetics, symphony）
scope-: 视野（如 telescope, microscope）
thermo-: 热（如 thermometer, thermostat）
vivo-: 生命（如 vivacious, revive）
zo-: 动物（如 zoology, zoo）
arch-: 主要（如 archenemy, archangel）
deca-: 十（如 decade, decathlon）
hexa-: 六（如 hexagon, hexadecimal）
octo-: 八（如 octopus, octagon）
quin-: 五（如 quintuplets, quinquennial）
tetra-: 四（如 tetrahedron, tetragon）
tri-: 三（如 triangle, tricycle）`
